//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Manager_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_dat_ban
    {
        public int id { get; set; }
        public Nullable<int> id_dat_ban { get; set; }
        public Nullable<int> id_ban { get; set; }
        public Nullable<int> id_phan_muc { get; set; }
    
        public virtual ban ban { get; set; }
        public virtual dat_ban dat_ban { get; set; }
        public virtual phan_muc_ban phan_muc_ban { get; set; }
    }
}
