//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Manager_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dat_ban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dat_ban()
        {
            this.chi_tiet_dat_ban = new HashSet<chi_tiet_dat_ban>();
            this.dat_ban_mon_an = new HashSet<dat_ban_mon_an>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_nguoi_dat { get; set; }
        public Nullable<int> id_nhan_vien { get; set; }
        public Nullable<System.DateTime> ngay_dat { get; set; }
        public Nullable<int> tien_coc_truoc { get; set; }
        public Nullable<System.DateTime> ngay_den { get; set; }
        public Nullable<int> so_luong_nguoi { get; set; }
        public Nullable<int> trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_dat_ban> chi_tiet_dat_ban { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dat_ban_mon_an> dat_ban_mon_an { get; set; }
    }
}
