//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Manager_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khuyen_mai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khuyen_mai()
        {
            this.chi_tiet_khuyen_mai = new HashSet<chi_tiet_khuyen_mai>();
        }
    
        public int id { get; set; }
        public string ten_dot_khuyen_mai { get; set; }
        public Nullable<System.DateTime> bat_dau { get; set; }
        public Nullable<System.DateTime> ket_thuc { get; set; }
        public Nullable<int> phan_tram_giam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_khuyen_mai> chi_tiet_khuyen_mai { get; set; }
    }
}
