//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Manager_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mon_an
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mon_an()
        {
            this.chi_tiet_danh_muc = new HashSet<chi_tiet_danh_muc>();
            this.chi_tiet_dat_hang = new HashSet<chi_tiet_dat_hang>();
            this.chi_tiet_hoa_don = new HashSet<chi_tiet_hoa_don>();
            this.chi_tiet_khuyen_mai = new HashSet<chi_tiet_khuyen_mai>();
            this.danh_gia_khach_hang = new HashSet<danh_gia_khach_hang>();
            this.dat_ban_mon_an = new HashSet<dat_ban_mon_an>();
        }
    
        public int id { get; set; }
        public string ten_mon_an { get; set; }
        public Nullable<int> gia { get; set; }
        public Nullable<System.DateTime> ngay_them { get; set; }
        public Nullable<System.DateTime> ngay_sua { get; set; }
        public Nullable<int> trang_thai { get; set; }
        public string hinh_anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_danh_muc> chi_tiet_danh_muc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_dat_hang> chi_tiet_dat_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_khuyen_mai> chi_tiet_khuyen_mai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danh_gia_khach_hang> danh_gia_khach_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dat_ban_mon_an> dat_ban_mon_an { get; set; }
    }
}
