//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Manager_4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tin_tuc
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ngay_viet { get; set; }
        public string tieu_de { get; set; }
        public string noi_dung { get; set; }
        public Nullable<int> id_nguoi_viet { get; set; }
    
        public virtual user user { get; set; }
    }
}
